//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KirovCentralParkFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enter
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LastEnter { get; set; }
        public Nullable<bool> TypeOfEnter { get; set; }
        public string CodeEmploee { get; set; }
    
        public virtual Emploee Emploee { get; set; }
    }
}
