//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KirovCentralParkFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderService
    {
        public int ID { get; set; }
        public string CodeOrder { get; set; }
        public int IDService { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual ServiceImp ServiceImp { get; set; }
    }
}
